import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ThemeToggle } from "@/components/ThemeToggle";
import Image from "next/image";
import BG from "@public/bg-img.jpg";
import footerImg from "@public/rick-and-morty-footer-img.jpg";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rick and Morty test app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Image
            src={BG}
            alt={"background image"}
            className="fixed inset-0 -z-10 h-full object-cover blur-sm"
          />

          <NavBar />

          <div className="fixed bottom-4 right-4">
            <ThemeToggle />
          </div>

          {children}

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
